tab = int(input('Digite um número para calcular a tabuada : '))
print('A tabudada deo {} é: '.format(tab))
print(15*'-')
print('{} x 1 = {} '.format(tab, tab*1))
print('{} x 1 = {} '.format(tab, tab*2))
print('{} x 1 = {} '.format(tab, tab*3))
print('{} x 1 = {} '.format(tab, tab*4))
print('{} x 1 = {} '.format(tab, tab*5))
print('{} x 1 = {} '.format(tab, tab*6))
print('{} x 1 = {} '.format(tab, tab*7))
print('{} x 1 = {} '.format(tab, tab*8))
print('{} x 1 = {} '.format(tab, tab*9))
print('{} x 1 = {} '.format(tab, tab*10))
print(15*'-')
